# Generated by Django 4.1.5 on 2023-01-15 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('municipality', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Biratnagar', 'Biratnagar'), ('Pokhara', 'Pokhara'), ('Laltipur', 'Lalitpur'), ('Birgunj', 'Birgunj'), ('Bharatpur', 'Bharatpur')], default='a', max_length=20)),
                ('downvote', models.ManyToManyField(blank=True, null=True, related_name='idea_dislikes', to=settings.AUTH_USER_MODEL)),
                ('upvote', models.ManyToManyField(blank=True, null=True, related_name='idea_likes', to=settings.AUTH_USER_MODEL)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('municipality', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Biratnagar', 'Biratnagar'), ('Pokhara', 'Pokhara'), ('Laltipur', 'Lalitpur'), ('Birgunj', 'Birgunj'), ('Bharatpur', 'Bharatpur')], default='a', max_length=50)),
                ('severity', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=0, max_length=50)),
                ('department', models.CharField(choices=[('road', 'road'), ('water', 'water'), ('transportation', 'transportation'), ('education', 'education'), ('information technology', 'information technology'), ('finance', 'finance'), ('foreign affairs', 'foreign affairs'), ('agriculture', 'agriculture'), ('health', 'health')], default='road', max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('downvote', models.ManyToManyField(blank=True, null=True, related_name='complain_dislikes', to=settings.AUTH_USER_MODEL)),
                ('upvote', models.ManyToManyField(blank=True, null=True, related_name='complain_likes', to=settings.AUTH_USER_MODEL)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
