# Generated by Django 4.1.7 on 2023-02-15 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='complain_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complain',
            name='municipality',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Biratnagar', 'Biratnagar'), ('Pokhara', 'Pokhara'), ('Laltipur', 'Lalitpur'), ('Birgunj', 'Birgunj'), ('Bharatpur', 'Bharatpur')], default='Kathmandu', max_length=50),
        ),
        migrations.AlterField(
            model_name='complain',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='complain_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='idea',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='idea_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='idea',
            name='municipality',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Biratnagar', 'Biratnagar'), ('Pokhara', 'Pokhara'), ('Laltipur', 'Lalitpur'), ('Birgunj', 'Birgunj'), ('Bharatpur', 'Bharatpur')], default='Kathmandu', max_length=50),
        ),
        migrations.AlterField(
            model_name='idea',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='idea_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
